site_name: Proyecto ML de Emociones en Música Turca
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          selection:
            docstring_style: google
nav:
  - Inicio: "index.md"
  - Pendientes: "guia.md"
  - Primeros Pasos:
      - "Instalación": "getting-started/installation.md"
      - "Configuración del Proyecto": "getting-started/project-setup.md"
  - Datos:
      - "Descripción General de Datos": "data/overview.md"
      - "Pipeline de Datos": "data/pipeline.md"
      - "Versionado de Datos": "data/versioning.md"
  - Modelo:
      - "Arquitectura del Modelo": "model/architecture.md"
      - "Pipeline de Entrenamiento": "model/training.md"
      - "Versionado del Modelo": "model/versioning.md"
      - "Seguimiento de Experimentos": "model/experiments.md"
  - MLOps:
      - "Pipeline": "mlops/pipeline.md"
      - "Automatización de Pipeline": "mlops/automation.md"
      - "Guía de Reproducibilidad": "mlops/reproducibility.md"
      - "Configuración del Entorno": "mlops/environment.md"
  - Referencia de API:
      - "Pipeline": "api/pipeline.md"
      - "Modelos": "api/models.md"
      - "Utilidades": "api/utils.md"
  - API:
      - "Descripción General": "api/index.md"
      - "Conjunto de Datos": "api/dataset.md"
      - "Configuración": "api/config.md"
      - "Selección de Características": "api/feature_selection.md"
      - "Características": "api/features.md"
      - "Evaluación del Modelo": "api/model_evaluation_utils.md"
      - "Entrenamiento": "api/modeling_train.md"
      - "Predicción": "api/modeling_predict.md"
      - "Gráficos": "api/plots.md"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - toc:
      permalink: true
