data:
  raw_filename: "Acoustic Features.csv"
  processed_filename: "Acoustic_Features_Processed.csv"

model:
  output_filename: "model.joblib"
  le_filename: 'label_encoder.joblib'
  split_indices_filename: 'split_indices.json'
  type: 'svm' # Acepta los parámetros 'rf' o 'svm' o 'knn'
  test_size: 0.2
  random_state: 1
  hyperparameters:
    rf:
      n_estimators: 50
      max_depth: 5
    svm:
      C: 0.5
      kernel: 'rbf'
      gamma: 'scale'
    knn:
      n_neighbors: 5

predict:
  input_file: 'data/test/test_data.csv'
